environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.ci\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

cache:
  - "C:\\pip_cache"

branches:
  except:
    - /^sils\/.*/

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%;

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - >
    "%CMD_IN_ENV% c:\python34\python.exe -m pip install --upgrade pip setuptools
  - >
    "%CMD_IN_ENV% python -m pip install
    --cache-dir=C:\\pip_cache -r requirements.txt -r test-requirements.txt

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%CMD_IN_ENV% pytest"
  - "%CMD_IN_ENV% python setup.py install"

matrix:
  fast_finish: true
